<?php namespace Socklab\Content;

use Backend\Models\User;
use October\Rain\Database\Model;
use Socklab\Content\Models\Team;
use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        User::extend(function (Model $model){

        });
    }
}
