title: Work
modelClass: Socklab\Content\Models\Work
list: $/socklab/content/models/work/columns.yaml
recordUrl: 'socklab/content/work/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
