title: Tag
modelClass: Socklab\Content\Models\Tag
list: $/socklab/content/models/tag/columns.yaml
recordUrl: 'socklab/content/tag/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
