title: Category
modelClass: Socklab\Content\Models\Category
list: $/socklab/content/models/category/columns.yaml
recordUrl: 'socklab/content/category/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
